services:
  db:
    image: ankane/pgvector
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=my_pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pgvector

volumes:
  db: