[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "npx prisma migrate deploy"
startCommand = "npm run start:prod"
healthcheckPath = "/healthz"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
